name: deploy-ec2

on:
  push:
    branches:
      - main
      - dev

env:
  S3_BUCKET_NAME: trilo-system-deploy
  PROJECT_NAME: trilo

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: trilo_db_test
      DB_ROOT_PASSWORD: root
      DB_USER: test
      DB_USER_PASSWORD: db1004

    steps:
      - name: Check Out (체크 아웃)
        uses: actions/checkout@v3

      - name: Start Redis (레디스 시작)
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 7.0.7

      - name: Set up MySQL (MySQL 설정)
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE ${{ env.DB_DATABASE }};" -uroot -p${{ env.DB_ROOT_PASSWORD }}
          mysql -e "CREATE user '${{ env.DB_USER }}'@'%' IDENTIFIED BY '${{ env.DB_USER_PASSWORD }}';" -uroot -p${{ env.DB_ROOT_PASSWORD }}
          mysql -e "GRANT ALL ON *.* TO 'test'@'%';" -uroot -p${{ env.DB_ROOT_PASSWORD }}
          mysql -e "FLUSH PRIVILEGES;" -uroot -p${{ env.DB_ROOT_PASSWORD }}

      - name: Set up JDK 17 (JDK 17 설치)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Use Gradle Cache (Gradle 캐싱)
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew (gradlew에 권한 부여)
        run: chmod +x gradlew
        shell: bash

      - name: Build (빌드)
        run: ./gradlew build

      - name: Make zip file (zip 으로 압축)
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials (AWS 인증 설정)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 (S3에 업로드)
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: CodeDeploy (CodeDeploy를 통해 EC2에 전달)
        run: aws deploy create-deployment --application-name trilo-system-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name develop --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
